HW1
Khabutdinov-Arslan/smart-home-2021 pull request #1
Opened 2021-03-10 19:37 UTC by Khabutdinov-Arslan

Class decomposition

2021-03-13 16:57 UTC, a-ivanov requested changes

2021-03-13 16:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/JSONSmartHomeReader.java
> +    String filename;
`private final`. И еще лучше поля перенести вверх перед конструктором.

2021-03-13 16:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventLoop.java
> +        LightEventHandler lightEventHandler = new LightEventHandler(smartHome);
DIP: создайте все обработчики в `main`, передайте сюда через конструктор.

2021-03-13 16:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventLoop.java
> +        RandomSensorEventGenerator generator = new RandomSensorEventGenerator();
DIP, см. выше.

2021-03-13 16:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventLoop.java
> +        DoorEventHandler doorEventHandler = new DoorEventHandler(smartHome);
DIP, см. выше.

2021-03-13 16:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventLoop.java
> +            if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
OCP: перепишите так, чтобы можно было добавлять новые обработчики без модификации этого кода.

2021-03-13 16:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventLoop.java
> +        LightEventHandler lightEventHandler = new LightEventHandler(smartHome);
(Hint) Создайте `List<EventHandler>`.

2021-03-13 16:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventLoop.java
> +        LightEventHandler lightEventHandler = new LightEventHandler(smartHome);
А где код `LightEventHandler`?

2021-03-13 16:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +                        if (room.getName().equals("hall")) {
SRP: обрабатывайте сценарии в отдельном классе.

2021-03-17 15:59 UTC, Khabutdinov-Arslan commented
added fixes

2021-03-18 05:02 UTC, a-ivanov requested changes

2021-03-18 05:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        ArrayList<EventHandler> handlers = new ArrayList<>();
`List` объявляйте переменные интерфейсом

2021-03-18 05:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventLoop.java
> +        RandomSensorEventGenerator generator = new RandomSensorEventGenerator();
Не исправлено.

2021-03-22 06:12 UTC, a-ivanov requested changes

2021-03-22 06:12 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/DoorEventHandler.java
> +            if (room.getName().equals("hall")) {
Не нужно привязывать логику холла к логике дверей. Имя "холл" - это деталь реализации обработчика сценариев.

2021-03-23 05:34 UTC, a-ivanov approved these changes

2021-03-24 16:00 UTC, merged