Hometask2v2
Khabutdinov-Arslan/smart-home-2021 pull request #2
Opened 2021-03-17 19:13 UTC by Khabutdinov-Arslan

New branch from most recent hometask1 version

2021-03-18 15:49 UTC, a-ivanov reviewed
Удалите все методы с доступом к внутренним объектам дома.

2021-03-18 15:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void execute(Action action){
Дом тоже можно обрабатывать.

2021-03-18 15:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHomeHelpers.java
> +    static boolean isHallDoor(SmartHome smartHome, String id){
Это на удаление, теперь работа с домом только через execute.

2021-03-18 15:49 UTC, a-ivanov requested changes
Доделайте.

2021-03-21 15:34 UTC, kieraCurtis commented on src/test/java/ru/sbt/mipt/oop/EventHandlersTest.java
> +    public void HandleDoorOpenTest(){
I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

2021-03-22 06:22 UTC, a-ivanov requested changes

2021-03-22 06:22 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/components/Room.java
> +    public Collection<Light> getLights() {
Удалите.

2021-03-23 05:32 UTC, a-ivanov approved these changes

2021-03-24 16:06 UTC, merged