HW 3 done
Khabutdinov-Arslan/smart-home-2021 pull request #3
Opened 2021-03-24 19:17 UTC by Khabutdinov-Arslan

2021-03-29 04:59 UTC, a-ivanov requested changes

2021-03-29 04:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/SimpleHandlerManager.java
> +    private ArrayList<EventHandler> handlers;
`List<Handler>`

2021-03-29 04:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/Alarm.java
> +        if ((state.equals(AlarmState.ACTIVATED) || state.equals(AlarmState.ALARM)) && (password == this.code)){
Логика по переходу - в отдельных (3х) классах состояния.

2021-03-29 04:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/AlarmState.java
> +public enum AlarmState {
Сделайте интерфейсом, реализуйте для 3х случаев.

2021-03-29 04:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/AlarmedHandlerManager.java
> +            switch (alarm.getState()){
Переделайте getState на методы, которые проверяют, включена ли сейчас сигнализация или нет (возвращают boolean). Не раскрывайте деталей реализации.

2021-04-05 17:01 UTC, a-ivanov requested changes

2021-04-05 17:01 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/alarm/Alarm.java
> +        state.handleEvent(event);
Нарушение SRP, обработчики в отдельном классе

2021-04-05 17:01 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/AlarmState.java
> +public interface AlarmState {
См. Текст задания,  должно быть 3 метода.

2021-04-05 17:01 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/alarm/AlarmFiring.java
> +        System.out.println("Alarm");
В отдельном классе

2021-04-05 17:01 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/alarm/AlarmFiring.java
> +        if (event.getType() instanceof SensorEventAlarmDeactivate){
Это все логика обработчика + декоратора, нарушение SRP

2021-04-12 06:34 UTC, a-ivanov requested changes
Перечитайте, как имплементировать шаблон декоратор, и переделайте декоратор для сигнализации.

2021-04-12 06:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/alarm/Alarm.java
> +    public void setState(AlarmState state){
Package private, инкапсуляция.

2021-04-12 06:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/alarm/AlarmedEventHandler.java
> +        this.notifier = new AlarmNotifier();
Передавайте через конструктор, DIP

2021-04-13 09:31 UTC, Khabutdinov-Arslan commented
> Перечитайте, как имплементировать шаблон декоратор, и переделайте декоратор для сигнализации.

public class AlarmedEventHandler implements EventHandler

Тело обработчика разбухло, поэтому я решил просто внутри выделить цепочку ответственности, в каждом звене которой понемногу логики

2021-04-13 17:35 UTC, a-ivanov commented
Ок, тогда по порядку.
Во-первых, цепочку можно написать без родительского класса, который просто таскает лишние для некорых звеньев поля, и сеттеров. Просто передавать нужные поля обработчику-звену.
Во-вторых, сейчас, если придёт два раза событие "активировать сигнализацию", у вас сигнализация не сработает, а по заданию после её активации обработка событий должна прекращать я, должно отправляться смс.
Так что давайте придерживаться требований в задании. Паттерны в нем выбраны не случайно, попрошу переделать задание с имплементацией декоратора.

2021-04-27 06:41 UTC, a-ivanov requested changes

2021-04-27 06:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
>          handlers.add(new LightEventHandler(smartHome));
Не вижу, чтобы декоратор сигнализации по заданию был применён в конфигурации приложения, доделайте.

2021-04-28 05:42 UTC, a-ivanov approved these changes

2021-04-28 07:05 UTC, merged