HW 4 done
Khabutdinov-Arslan/smart-home-2021 pull request #4
Opened 2021-04-04 08:36 UTC by Khabutdinov-Arslan

2021-04-05 17:05 UTC, a-ivanov requested changes

2021-04-05 17:05 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Config.java
> +public class Config {
`@Configuration`

2021-04-05 17:05 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/CCSensorEventAdaptor.java
> +        convertor.put("LightIsOn", new SensorEventLightOn());
Перенесите в бин в конфигурацию.

2021-04-28 15:20 UTC, Khabutdinov-Arslan commented on src/main/java/ru/sbt/mipt/oop/events/CCSensorEventAdaptor.java
> +        convertor.put("LightIsOn", new SensorEventLightOn());
Что именно? Adapter же создаётся отдельно для каждого обработчика, а не один раз.

2021-04-28 16:32 UTC, a-ivanov approved these changes

2021-04-28 16:32 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/CCSensorEventAdaptor.java
> +    private final HashMap <String, SensorEventType> convertor;
Map

2021-04-28 18:24 UTC, merged